const products = [
  { id: 1, name: 'Second Skin Tint', type: 'face', label: 'Face · 12 shades', price: 32, img: 'assets/skin-tint.svg', badge: 'Bestseller' },
  { id: 2, name: 'Cloud Cream Blush', type: 'face', label: 'Face · 6 shades', price: 24, img: 'assets/cream-blush.svg', badge: 'New' },
  { id: 3, name: 'Soft Focus Lip Oil', type: 'lips', label: 'Lips · 5 shades', price: 22, img: 'assets/lip-oil.svg', badge: '' },
  { id: 4, name: 'After Hours Palette', type: 'eyes', label: 'Eyes · 8 shades', price: 38, img: 'assets/eye-palette.svg', badge: 'Limited' }
];
let activeFilter = 'all', bag = [];
const productEl = document.querySelector('#products'), money = n => `₦${n.toFixed(2)}`;
function renderProducts() { const selected = products.filter(p => activeFilter === 'all' || p.type === activeFilter); productEl.innerHTML = selected.map(p => `<article class="product"><div class="product-image"><img src="${p.img}" alt="${p.name}">${p.badge ? `<span class="badge">${p.badge}</span>` : ''}</div><button class="quick-add" onclick="addToBag(${p.id})" aria-label="Add ${p.name}">+</button><div class="product-info"><div><p class="product-name">${p.name}</p><p class="product-type">${p.label}</p></div><p class="price">${money(p.price)}</p></div></article>`).join('') }
function addToBag(id) { bag.push(products.find(p => p.id === id)); renderBag(); document.querySelector('#toast').classList.add('show'); setTimeout(() => document.querySelector('#toast').classList.remove('show'), 1800) }
function renderBag() { const total = bag.reduce((sum, p) => sum + p.price, 0); document.querySelector('#bagCount').textContent = bag.length; document.querySelector('#cartQuantity').textContent = bag.length; document.querySelector('#subtotal').textContent = money(total); document.querySelector('#cartItems').innerHTML = bag.length ? bag.map((p, i) => `<div class="cart-item"><img src="${p.img}" alt=""><div><h4>${p.name}</h4><p>${p.label}</p><p>${money(p.price)}</p></div><button class="remove" onclick="removeItem(${i})">×</button></div>`).join('') : '<p class="empty">Your bag is waiting for something lovely.</p>' }
function removeItem(i) { bag.splice(i, 1); renderBag() }
function toggleCart(open) { document.querySelector('#cart').classList.toggle('open', open); document.querySelector('#overlay').classList.toggle('show', open); document.querySelector('#cart').setAttribute('aria-hidden', !open) }
document.querySelectorAll('.filters button').forEach(b => b.onclick = () => { document.querySelector('.filters .active').classList.remove('active'); b.classList.add('active'); activeFilter = b.dataset.filter; renderProducts() });
document.querySelector('#bagCount').parentElement.onclick = () => toggleCart(true); document.querySelector('#closeCart').onclick = () => toggleCart(false); document.querySelector('#overlay').onclick = () => toggleCart(false);
const menuButton = document.querySelector('.menu-button'); const primaryNavigation = document.querySelector('#primaryNavigation');
menuButton.onclick = () => { const isOpen = primaryNavigation.classList.toggle('mobile-open'); menuButton.setAttribute('aria-expanded', String(isOpen)); menuButton.setAttribute('aria-label', isOpen ? 'Close menu' : 'Open menu'); };
primaryNavigation.querySelectorAll('a').forEach(link => link.onclick = () => { primaryNavigation.classList.remove('mobile-open'); menuButton.setAttribute('aria-expanded', 'false'); menuButton.setAttribute('aria-label', 'Open menu'); });
document.querySelector('#checkoutButton').onclick = () => { if (!bag.length) { document.querySelector('#toast').textContent = 'Add something to your bag first'; document.querySelector('#toast').classList.add('show'); setTimeout(() => document.querySelector('#toast').classList.remove('show'), 1800); return } toggleCart(false); document.querySelector('#checkout').classList.add('open'); document.querySelector('#checkout').setAttribute('aria-hidden', 'false'); const total = bag.reduce((s, p) => s + p.price, 0); document.querySelector('#checkoutItems').innerHTML = bag.map(p => `<div class="checkout-line"><span>${p.name}</span><span>${money(p.price)}</span></div>`).join(''); document.querySelector('#checkoutTotal').textContent = money(total) };
document.querySelector('#closeCheckout').onclick = () => document.querySelector('#checkout').classList.remove('open');
function showPaymentError(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000) }
async function makeFlutterwavePayment() { const email = document.querySelector('#checkoutEmail').value.trim(), name = document.querySelector('#checkoutName').value.trim(), payButton = document.querySelector('#payButton'); const amount = Number(bag.reduce((total, item) => total + item.price, 0).toFixed(2)); const items = bag.reduce((entries, item) => { const match = entries.find(entry => entry.id === item.id); if (match) match.quantity += 1; else entries.push({ id: item.id, quantity: 1 }); return entries }, []); if (!email) { document.querySelector('#checkoutEmail').focus(); return } if (!name) { document.querySelector('#checkoutName').focus(); return } if (!amount) { showPaymentError('Add an item to your bag before paying.'); return } payButton.disabled = true; payButton.textContent = 'Creating secure checkout…'; try { const response = await fetch('/api/create-payment', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ amount, email, name, items }) }); const data = await response.json(); if (!response.ok || !data.link) throw new Error(data.error || 'Flutterwave could not create a checkout link.'); window.location.assign(data.link); } catch (error) { showPaymentError(error.message); payButton.disabled = false; payButton.innerHTML = 'Pay with Flutterwave <span>→</span>'; } }
document.querySelector('#payButton').addEventListener('click', makeFlutterwavePayment);
document.querySelector('#viewAll').onclick = () => { activeFilter = 'all'; document.querySelectorAll('.filters button').forEach(x => x.classList.toggle('active', x.dataset.filter === 'all')); renderProducts(); document.querySelector('#shop').scrollIntoView() }; renderProducts();

